services:
    elasticsearch:
      container_name: "elasticsearch"
      image: elasticsearch:8.12.1
      expose:
        - ${ELASTICSEARCH_PORT}
      volumes:
        - ./services/es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
        - ./services/es/data:/usr/share/elasticsearch/data
      healthcheck:
        test: ["CMD-SHELL", "curl -s http://localhost:${ELASTICSEARCH_PORT}/_cat/health?h=status | grep -q green"]
        retries: 30
        interval: 3s
      deploy:
        resources:
          limits:
            memory: 4GB

    kibana:
      container_name: "kibana"
      image: kibana:8.12.1
      expose:
        - ${KIBANA_PORT}
      depends_on: 
        - elasticsearch
      env_file:
        - .env
      volumes:
        - "./services/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:${KIBANA_PORT}"]
        retries: 300
        interval: 2s

    search:
      container_name: search
      build: ./services/search
      volumes:
        - ./services/search:/app:ro
        - ./services/search/logs:/app/logs
        - ./services/search/data:/app/data
      healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:${SEARCH_SERVICE_PORT}/health || exit 1"]
        retries: 30
        interval: 3s
      env_file:
        - .env
      depends_on:
        - elasticsearch

    nginx:
      container_name: "nginx"
      restart: always
      build: ./services/nginx
      volumes:
        - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./services/nginx/configs:/etc/nginx/conf.d:ro
        - ./services/nginx/logs:/var/log/nginx/
      ports:
        - ${NGINX_PORTS}

    etl:
      container_name: "etl"
      build: ./services/etl
      volumes:
        - ./services/etl:/app:ro
        - ./services/etl/logs:/app/logs
      env_file:
        - .env
      depends_on: 
        elasticsearch:
          condition: service_healthy